name: Whiteboard
main: net.nando256.whiteboard.WhiteboardPlugin
version: ${version}
api-version: '1.21.9'
authors: [ 'nando256' ]
description: 'Whiteboard for Paper: stitch item-frame maps into a board; render text/HTML, backgrounds, undo/redo, locking, fonts.'
commands:
  whiteboard:
    description: 'Whiteboard base command'
    usage: |
      /whiteboard grid <WxH>
      /whiteboard text <msg> [size] [#RRGGBB]
      /whiteboard htext <html> [size] [#RRGGBB]
      /whiteboard bg <#RRGGBB>
      /whiteboard clear | undo | redo | lock <on|off> | font <family> [style]
    aliases: [ wb ]

