name: Publish to Hangar

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Determine channel & version
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "channel=Release" >> $GITHUB_OUTPUT
            # 例: v1.2.3 → 1.2.3
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "channel=Snapshot" >> $GITHUB_OUTPUT
            echo "version=0.0.0-${GITHUB_SHA::7}-SNAPSHOT" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: ./gradlew -q clean build

      - name: Publish to Hangar
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: |
          ./gradlew \
            -Phangar.channel=${{ steps.meta.outputs.channel }} \
            -Pversion.override=${{ steps.meta.outputs.version }} \
            publishPluginPublicationToHangar
